modLoader="javafml"
loaderVersion="[47,)"
license='MIT'

[[mods]]
modId="extrememetals"
version="1.30.62-legacy"
displayName="Extreme Metals"
authors="Surubedai"
description='''add some metals and machines'''

[[dependencies.extrememetals]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.extrememetals]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"

[[dependencies.extrememetals]]
    modId="jei"
    mandatory=false
    versionRange="[15.2.0.20,)"
    ordering="AFTER"
    side="BOTH"
